Repository NguyenLoan04/WebTranhTheu_LTWEB_NLU_NHOM26, pull requests merged in 2025-02, with the labels that each got.

#78 Cập nhật chức năng quản lý khuyến mãi
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/order/GetFormReadEditOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/order/GetOrderDataController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/order/OrderManagementController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/order/UpdateOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/product/AddProductController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/promotion/AddPromotionController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/promotion/DeletePromotionController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/promotion/GetFormAddPromotionController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/promotion/GetFormReadUpdatePromotionController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/admin/promotion/UpdatePromotionController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/DiscountDAO.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/ProductDAO.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/services/DiscountService.java
  src/main/webapp/layout/admin/admin.jsp
  src/main/webapp/layout/admin/category-form/read-edit-category-form.jsp
  src/main/webapp/layout/admin/manage-promotion.jsp
  src/main/webapp/layout/admin/product-form/add-product-form.jsp
  src/main/webapp/layout/admin/promotion-form/add-promotion-form.jsp
  src/main/webapp/layout/admin/promotion-form/delete-popup.jsp
  src/main/webapp/layout/admin/promotion-form/read-edit-promotion-form.jsp
  src/main/webapp/layout/admin/topic-form/read-edit-topic-form.jsp
  src/main/webapp/template/script/admin/change-promotion-form.js
  src/main/webapp/template/script/admin/promotion-form/read-edit-promotion-form.js
  src/main/webapp/template/script/admin/provider-form/read-edit-provider-form.js
Labels: update feaure

#75 Chỉnh sửa và hoàn thiện giao diện
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/ProductDAO.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/services/product/DisplayFullProduct.java
  src/main/webapp/index.jsp
  src/main/webapp/layout/category.jsp
  src/main/webapp/layout/error.jsp
  src/main/webapp/layout/forget-password.jsp
  src/main/webapp/layout/product.jsp
  src/main/webapp/layout/public/footer.jsp
  src/main/webapp/layout/public/header.jsp
  src/main/webapp/layout/public/library.jsp
  src/main/webapp/layout/search.jsp
  src/main/webapp/layout/sign-in.jsp
  src/main/webapp/layout/sign-up.jsp
  src/main/webapp/layout/user/cart.jsp
  src/main/webapp/layout/user/orders/cancel-orders.jsp
  src/main/webapp/layout/user/orders/pickup-orders.jsp
  src/main/webapp/layout/user/orders/received-orders.jsp
  src/main/webapp/layout/user/orders/shipped-orders.jsp
  src/main/webapp/layout/user/orders/shipping-orders.jsp
  src/main/webapp/layout/user/orders/turnback-orders.jsp
  src/main/webapp/layout/user/orders/waitlist-orders.jsp
  src/main/webapp/layout/user/review-form/read-review-detail.jsp
  src/main/webapp/layout/user/user-addresses.jsp
  src/main/webapp/layout/user/user-feedbacks.jsp
  src/main/webapp/layout/user/user-help.jsp
  src/main/webapp/layout/user/user-info.jsp
  src/main/webapp/layout/user/user-orders.jsp
  src/main/webapp/layout/user/user-setting.jsp
  src/main/webapp/layout/user/user-viewed-info.jsp
  src/main/webapp/layout/user/user-wishlist.jsp
  src/main/webapp/layout/user/user.jsp
  src/main/webapp/template/asset/favicon/favicon.ico
  src/main/webapp/template/asset/favicon/web_logo_revert_color.png
  src/main/webapp/template/asset/image/404image.png
  src/main/webapp/template/asset/image/VNPay.png
  src/main/webapp/template/asset/image/error404.png
  src/main/webapp/template/asset/image/momo-logo.png
  src/main/webapp/template/asset/image/product_image.png
  src/main/webapp/template/script/account/account.js
  src/main/webapp/template/script/category.js
  src/main/webapp/template/script/home.js
  src/main/webapp/template/script/search.js
  src/main/webapp/template/style/index.css
  src/main/webapp/template/style/style.css
  src/main/webapp/template/style/user/account-page.css
  src/main/webapp/template/style/user/category.css
  src/main/webapp/template/style/user/product.css
Labels: update feaure, large pr, fixed bug

#80 Sửa phần hiển thị Chi tiết đơn hàng
  src/main/webapp/layout/user/orders/order-form/read-detail-order.jsp
  src/main/webapp/template/style/user/style-forms/orders.css
Labels: update feaure

#79 Hoàn thiện phần hiển thị địa chỉ giao hàng
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/auth/LoginController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/product/ProductController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/purchase/PerformPurchase.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/purchase/PurchaseController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/OrderDAO.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/services/PurchaseOperator.java
  src/main/webapp/layout/product.jsp
  src/main/webapp/layout/purchase.jsp
  src/main/webapp/template/script/purchase.js
Labels: full enchancement, update feaure, fixed bug

#81 Thêm phần filter
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/filter/AdminFilter.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/filter/JSPFilter.java
Labels: full enchancement, update feaure

#82 Fix các lỗi còn tồn đọng
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/OrderDAO.java
  src/main/webapp/layout/public/library.jsp
  src/main/webapp/layout/purchase.jsp
Labels: fixed bug

#83 Thêm dockerfile và fix các lỗi còn tồn đọng
  Dockerfile
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/bean/user/User.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/auth/GoogleLoginController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/purchase/PurchaseController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/HelpController.java
  src/main/webapp/layout/product.jsp
  src/main/webapp/layout/user/user.jsp
  src/main/webapp/template/script/product.js
Labels: fixed bug

#84 Thêm LICENSE và README vào repo
  LICENSE
  README.md
Labels: update structure

#86 Cập nhật giao diện web
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/bean/product/Product.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/bean/user/order/Order.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/product/UploadProductReview.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/CancelOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/PickupOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/ReceivedOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/ShippedOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/ShippingOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/TurnbackOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/WaitlistOrderController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/controller/user/order/order_form/AddOrderToCartController.java
  src/main/java/com/example/webtranhtheu_ltweb_nlu_nhom26/dao/ProductDAO.java
  src/main/webapp/layout/product.jsp
  src/main/webapp/layout/user/orders/cancel-orders.jsp
  src/main/webapp/layout/user/orders/order-form/read-cancel-order.jsp
  src/main/webapp/layout/user/orders/order-form/read-detail-order.jsp
  src/main/webapp/layout/user/orders/orders-detail.jsp
  src/main/webapp/layout/user/orders/pickup-orders.jsp
  src/main/webapp/layout/user/orders/received-orders.jsp
  src/main/webapp/layout/user/orders/shipped-orders.jsp
  src/main/webapp/layout/user/orders/shipping-orders.jsp
  src/main/webapp/layout/user/orders/turnback-orders.jsp
  src/main/webapp/layout/user/orders/waitlist-orders.jsp
  src/main/webapp/layout/user/review-form/read-review-detail.jsp
  src/main/webapp/layout/user/user-feedbacks.jsp
  src/main/webapp/layout/user/user-orders.jsp
  src/main/webapp/layout/user/user-setting.jsp
  src/main/webapp/static/script/account/user-feedback.js
  src/main/webapp/static/style/user/account-page.css
  src/main/webapp/static/style/user/style-forms/orders.css
  src/main/webapp/static/style/user/style-forms/user-setting.css
Labels: help wanted, good first issue, update feaure, large pr, fixed bug
